server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/ridex
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    ride-requested: ride-requested
    driver-accepted: driver-accepted

springdoc:
  swagger-ui:
    path: /swagger-ui.html
