server:
  port: 8084

spring:
  main:
    lazy-initialization: true
  application:
    name: trip-service
  datasource:
    url: jdbc:mysql://mysql:3306/ridex
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: trip-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        reconnect.backoff.ms: 2000
        reconnect.backoff.max.ms: 10000
        request.timeout.ms: 30000
        default.api.timeout.ms: 60000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html
