server:
  port: 8082

spring:
  main:
    lazy-initialization: true
  application:
    name: driver-service
  datasource:
    url: jdbc:mysql://mysql:3306/ridex
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: redis
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
