server:
  port: 8088

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ridex_analytics
    username: ridex
    password: ridex
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
